# Generated by Django 2.0.5 on 2018-06-24 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('is_admin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PrivateResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=200)),
                ('res_date', models.DateTimeField(verbose_name='response date')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contact.Person')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contact.Person')),
            ],
        ),
        migrations.CreateModel(
            name='PublicAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contact.Person')),
            ],
        ),
        migrations.CreateModel(
            name='PublicQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contact.Person')),
            ],
        ),
        migrations.AddField(
            model_name='publicanswer',
            name='public_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contact.PublicQuestion'),
        ),
        migrations.AddField(
            model_name='privateresponse',
            name='suggestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contact.PrivateSuggestion'),
        ),
    ]
